# Q).Perform Principal component analysis and perform clustering using first 3
#  principal component scores (both heirarchial and k mean clustering(scree plot or elbow curve) and obtain 
# optimum number of clusters and check whether we have obtained same number of clusters with the original data 
# (class column we have ignored at the begining who shows it has 3 clusters)df

In [1]:
#Importing Libraries

In [2]:
import numpy as np
import pandas as pd
df1 = pd.read_csv('wine.csv')
df1

Type  Alcohol  Malic   Ash  Alcalinity  Magnesium  Phenols  Flavanoids  \
0       1    14.23   1.71  2.43        15.6        127     2.80        3.06   
1       1    13.20   1.78  2.14        11.2        100     2.65        2.76   
2       1    13.16   2.36  2.67        18.6        101     2.80        3.24   
3       1    14.37   1.95  2.50        16.8        113     3.85        3.49   
4       1    13.24   2.59  2.87        21.0        118     2.80        2.69   
..    ...      ...    ...   ...         ...        ...      ...         ...   
173     3    13.71   5.65  2.45        20.5         95     1.68        0.61   
174     3    13.40   3.91  2.48        23.0        102     1.80        0.75   
175     3    13.27   4.28  2.26        20.0        120     1.59        0.69   
176     3    13.17   2.59  2.37        20.0        120     1.65        0.68   
177     3    14.13   4.10  2.74        24.5         96     2.05        0.76   

     Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Proline  
0             0.28             2.29   5.64  1.04      3.92     1065  
1             0.26             1.28   4.38  1.05      3.40     1050  
2             0.30             2.81   5.68  1.03      3.17     1185  
3             0.24             2.18   7.80  0.86      3.45     1480  
4             0.39             1.82   4.32  1.04      2.93      735  
..             ...              ...    ...   ...       ...      ...  
173           0.52             1.06   7.70  0.64      1.74      740  
174           0.43             1.41   7.30  0.70      1.56      750  
175           0.43             1.35  10.20  0.59      1.56      835  
176           0.53             1.46   9.30  0.60      1.62      840  
177           0.56             1.35   9.20  0.61      1.60      560  

[178 rows x 14 columns]

In [3]:
#Performing EDA

In [4]:
df1.describe().T

count        mean         std     min       25%      50%  \
Type             178.0    1.938202    0.775035    1.00    1.0000    2.000   
Alcohol          178.0   13.000618    0.811827   11.03   12.3625   13.050   
Malic            178.0    2.336348    1.117146    0.74    1.6025    1.865   
Ash              178.0    2.366517    0.274344    1.36    2.2100    2.360   
Alcalinity       178.0   19.494944    3.339564   10.60   17.2000   19.500   
Magnesium        178.0   99.741573   14.282484   70.00   88.0000   98.000   
Phenols          178.0    2.295112    0.625851    0.98    1.7425    2.355   
Flavanoids       178.0    2.029270    0.998859    0.34    1.2050    2.135   
Nonflavanoids    178.0    0.361854    0.124453    0.13    0.2700    0.340   
Proanthocyanins  178.0    1.590899    0.572359    0.41    1.2500    1.555   
Color            178.0    5.058090    2.318286    1.28    3.2200    4.690   
Hue              178.0    0.957449    0.228572    0.48    0.7825    0.965   
Dilution         178.0    2.611685    0.709990    1.27    1.9375    2.780   
Proline          178.0  746.893258  314.907474  278.00  500.5000  673.500   

                      75%      max  
Type               3.0000     3.00  
Alcohol           13.6775    14.83  
Malic              3.0825     5.80  
Ash                2.5575     3.23  
Alcalinity        21.5000    30.00  
Magnesium        107.0000   162.00  
Phenols            2.8000     3.88  
Flavanoids         2.8750     5.08  
Nonflavanoids      0.4375     0.66  
Proanthocyanins    1.9500     3.58  
Color              6.2000    13.00  
Hue                1.1200     1.71  
Dilution           3.1700     4.00  
Proline          985.0000  1680.00

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Type             178 non-null    int64  
 1   Alcohol          178 non-null    float64
 2   Malic            178 non-null    float64
 3   Ash              178 non-null    float64
 4   Alcalinity       178 non-null    float64
 5   Magnesium        178 non-null    int64  
 6   Phenols          178 non-null    float64
 7   Flavanoids       178 non-null    float64
 8   Nonflavanoids    178 non-null    float64
 9   Proanthocyanins  178 non-null    float64
 10  Color            178 non-null    float64
 11  Hue              178 non-null    float64
 12  Dilution         178 non-null    float64
 13  Proline          178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [6]:
df1.corr()

Type   Alcohol     Malic       Ash  Alcalinity  \
Type             1.000000 -0.328222  0.437776 -0.049643    0.517859   
Alcohol         -0.328222  1.000000  0.094397  0.211545   -0.310235   
Malic            0.437776  0.094397  1.000000  0.164045    0.288500   
Ash             -0.049643  0.211545  0.164045  1.000000    0.443367   
Alcalinity       0.517859 -0.310235  0.288500  0.443367    1.000000   
Magnesium       -0.209179  0.270798 -0.054575  0.286587   -0.083333   
Phenols         -0.719163  0.289101 -0.335167  0.128980   -0.321113   
Flavanoids      -0.847498  0.236815 -0.411007  0.115077   -0.351370   
Nonflavanoids    0.489109 -0.155929  0.292977  0.186230    0.361922   
Proanthocyanins -0.499130  0.136698 -0.220746  0.009652   -0.197327   
Color            0.265668  0.546364  0.248985  0.258887    0.018732   
Hue             -0.617369 -0.071747 -0.561296 -0.074667   -0.273955   
Dilution        -0.788230  0.072343 -0.368710  0.003911   -0.276769   
Proline         -0.633717  0.643720 -0.192011  0.223626   -0.440597   

                 Magnesium   Phenols  Flavanoids  Nonflavanoids  \
Type             -0.209179 -0.719163   -0.847498       0.489109   
Alcohol           0.270798  0.289101    0.236815      -0.155929   
Malic            -0.054575 -0.335167   -0.411007       0.292977   
Ash               0.286587  0.128980    0.115077       0.186230   
Alcalinity       -0.083333 -0.321113   -0.351370       0.361922   
Magnesium         1.000000  0.214401    0.195784      -0.256294   
Phenols           0.214401  1.000000    0.864564      -0.449935   
Flavanoids        0.195784  0.864564    1.000000      -0.537900   
Nonflavanoids    -0.256294 -0.449935   -0.537900       1.000000   
Proanthocyanins   0.236441  0.612413    0.652692      -0.365845   
Color             0.199950 -0.055136   -0.172379       0.139057   
Hue               0.055398  0.433681    0.543479      -0.262640   
Dilution          0.066004  0.699949    0.787194      -0.503270   
Proline           0.393351  0.498115    0.494193      -0.311385   

                 Proanthocyanins     Color       Hue  Dilution   Proline  
Type                   -0.499130  0.265668 -0.617369 -0.788230 -0.633717  
Alcohol                 0.136698  0.546364 -0.071747  0.072343  0.643720  
Malic                  -0.220746  0.248985 -0.561296 -0.368710 -0.192011  
Ash                     0.009652  0.258887 -0.074667  0.003911  0.223626  
Alcalinity             -0.197327  0.018732 -0.273955 -0.276769 -0.440597  
Magnesium               0.236441  0.199950  0.055398  0.066004  0.393351  
Phenols                 0.612413 -0.055136  0.433681  0.699949  0.498115  
Flavanoids              0.652692 -0.172379  0.543479  0.787194  0.494193  
Nonflavanoids          -0.365845  0.139057 -0.262640 -0.503270 -0.311385  
Proanthocyanins         1.000000 -0.025250  0.295544  0.519067  0.330417  
Color                  -0.025250  1.000000 -0.521813 -0.428815  0.316100  
Hue                     0.295544 -0.521813  1.000000  0.565468  0.236183  
Dilution                0.519067 -0.428815  0.565468  1.000000  0.312761  
Proline                 0.330417  0.316100  0.236183  0.312761  1.000000

In [7]:
#calculates the variance of each column in the DataFrame 

In [8]:
t1=df1.var()
t1

Type                   0.600679
Alcohol                0.659062
Malic                  1.248015
Ash                    0.075265
Alcalinity            11.152686
Magnesium            203.989335
Phenols                0.391690
Flavanoids             0.997719
Nonflavanoids          0.015489
Proanthocyanins        0.327595
Color                  5.374449
Hue                    0.052245
Dilution               0.504086
Proline            99166.717355
dtype: float64

In [9]:
#perform (PCA) on your DataFrame df1. PCA is a technique used for dimensionality reduction.

In [10]:
from sklearn.decomposition import PCA
pca = PCA()
pc=pca.fit_transform(df1)

In [11]:
#converted the NumPy array pc (resulting from PCA) into a Pandas DataFrame and assigned column names to it

In [12]:
pc = pd.DataFrame(pc)
pc.columns = list(df1)
pc

Type    Alcohol     Malic       Ash  Alcalinity  Magnesium  \
0    318.564055  21.490773  3.164613 -0.260166    0.752092   0.520109   
1    303.098514  -5.366083  6.816992 -1.004978   -0.501045   0.052439   
2    438.062063  -6.537986 -1.066717  0.977727    0.453208   0.634322   
3    733.240711   0.193320 -0.938312 -0.525349    0.879918   0.480810   
4    -11.569952  18.487255 -0.424917  1.518823    0.506733   0.862531   
..          ...        ...       ...       ...         ...        ...   
173   -6.981858  -4.538116 -2.625187 -3.214097   -2.204812   1.644655   
174    3.129945   2.338236 -4.423240 -1.576971   -1.184902   0.206914   
175   88.456310  18.779644 -2.423127 -4.874280   -1.002718   0.319367   
176   93.454472  18.674180 -1.958775 -3.789964   -0.399558  -1.011081   
177 -186.944619  -0.211063 -5.733920 -3.366462    0.186523   0.769307   

      Phenols  Flavanoids  Nonflavanoids  Proanthocyanins     Color       Hue  \
0   -0.590537   -0.212167      -0.676304         0.112542  0.140469  0.168879   
1    0.082171    0.614829      -0.238538         0.091296  0.087360  0.088933   
2    0.793768   -0.427185      -0.120496        -0.337593 -0.135517  0.180876   
3    0.100237    0.088945       0.071970         0.646950 -0.003737 -0.056476   
4   -0.405248    0.204093       0.111987        -0.280533 -0.552207  0.045926   
..        ...         ...            ...              ...       ...       ...   
173 -0.007924    0.016205      -0.006596         0.148824  0.032053  0.042729   
174  0.035870   -0.339823       0.171434         0.139584 -0.001735 -0.037202   
175  0.621932    0.124380      -0.289628        -0.027412  0.094686 -0.209746   
176  0.415895   -0.128919      -0.250348         0.104226  0.044378 -0.000322   
177 -0.691678   -0.273443       0.128688         0.166117 -0.298025  0.039295   

     Dilution   Proline  
0   -0.016430  0.089355  
1   -0.044845  0.017896  
2   -0.050358 -0.039421  
3   -0.157085  0.021160  
4   -0.056540 -0.011405  
..        ...       ...  
173  0.109068  0.034495  
174  0.016845 -0.039199  
175  0.085337  0.034372  
176 -0.046564  0.136469  
177  0.016019  0.019787  

[178 rows x 14 columns]

In [13]:
t1=pca.explained_variance_ratio_
t1

array([9.98087625e-01, 1.73591851e-03, 9.58948998e-05, 5.13200714e-05,
       1.29365230e-05, 8.73476385e-06, 2.88762342e-06, 1.56228669e-06,
       1.14428924e-06, 8.69067273e-07, 4.64851997e-07, 3.51409235e-07,
       2.08896603e-07, 8.14215462e-08])

In [14]:
t1[0]*100

99.80876253882408

In [15]:
sum(t1)

1.0000000000000002

In [16]:
pc.var()

Type               99202.030731
Alcohol              172.536596
Malic                  9.531196
Ash                    5.100810
Alcalinity             1.285788
Magnesium              0.868167
Phenols                0.287007
Flavanoids             0.155279
Nonflavanoids          0.113733
Proanthocyanins        0.086378
Color                  0.046203
Hue                    0.034927
Dilution               0.020763
Proline                0.008093
dtype: float64

In [17]:
# created a new DataFrame pc2 by selecting the first four principal components from the DataFrame

In [18]:
pc2 = pc.iloc[:,0:4]
pc2

Type    Alcohol     Malic       Ash
0    318.564055  21.490773  3.164613 -0.260166
1    303.098514  -5.366083  6.816992 -1.004978
2    438.062063  -6.537986 -1.066717  0.977727
3    733.240711   0.193320 -0.938312 -0.525349
4    -11.569952  18.487255 -0.424917  1.518823
..          ...        ...       ...       ...
173   -6.981858  -4.538116 -2.625187 -3.214097
174    3.129945   2.338236 -4.423240 -1.576971
175   88.456310  18.779644 -2.423127 -4.874280
176   93.454472  18.674180 -1.958775 -3.789964
177 -186.944619  -0.211063 -5.733920 -3.366462

[178 rows x 4 columns]

In [19]:
#assigned the DataFrame pc2 to a new variable X

In [20]:
X = pc2.iloc[:,:]
X

Type    Alcohol     Malic       Ash
0    318.564055  21.490773  3.164613 -0.260166
1    303.098514  -5.366083  6.816992 -1.004978
2    438.062063  -6.537986 -1.066717  0.977727
3    733.240711   0.193320 -0.938312 -0.525349
4    -11.569952  18.487255 -0.424917  1.518823
..          ...        ...       ...       ...
173   -6.981858  -4.538116 -2.625187 -3.214097
174    3.129945   2.338236 -4.423240 -1.576971
175   88.456310  18.779644 -2.423127 -4.874280
176   93.454472  18.674180 -1.958775 -3.789964
177 -186.944619  -0.211063 -5.733920 -3.366462

[178 rows x 4 columns]

In [21]:
#display Matplotlib plots in a separate interactive window 

In [22]:
%matplotlib qt
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (16,9)

In [23]:
# importing the Axes3D module from mpl_toolkits.mplot3d and using the warnings module to filter out warnings.

In [24]:
from mpl_toolkits.mplot3d import Axes3D
import warnings
warnings.filterwarnings('ignore')

In [25]:
# creating a 3D scatter plot using the Axes3D module from Matplotlib

In [26]:
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(X.iloc[:,0],X.iloc[:,1],X.iloc[:,3])
plt.show()

In [27]:
# single linkage using euclidean distance metric

In [28]:
from sklearn.cluster import AgglomerativeClustering
acs = AgglomerativeClustering(n_clusters=5,affinity='euclidean',linkage='single')
Y = acs.fit_predict(X)
Y

array([0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int64)

In [29]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [30]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
0           170
2             5
1             1
3             1
4             1
dtype: int64

In [31]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [32]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=acs.labels_, cmap='rainbow')

In [33]:
#creating a DataFrame Y_cluster based on some variable Y and then using value_counts() to count the occurrences of each unique value

In [34]:
Y_cluster = pd.DataFrame(Y)
Y_cluster.value_counts()

0    170
2      5
1      1
3      1
4      1
dtype: int64

In [35]:
# single linkage using manhattan distance metric

In [36]:
from sklearn.cluster import AgglomerativeClustering
acs1 = AgglomerativeClustering(n_clusters=5,affinity='manhattan',linkage='single')
Y = acs1.fit_predict(X)
Y

array([0, 0, 0, 2, 0, 2, 1, 1, 0, 0, 2, 1, 1, 0, 2, 1, 1, 0, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int64)

In [37]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [38]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.head()
Y_new.value_counts()

clusters
0           157
1            14
2             5
3             1
4             1
dtype: int64

In [39]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [40]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=acs1.labels_, cmap='rainbow')

In [41]:
# single linkage using l1 distance metric

In [42]:
acs2 = AgglomerativeClustering(n_clusters=5,affinity='l1',linkage='single')
Y = acs2.fit_predict(X)
Y

array([0, 0, 0, 2, 0, 2, 1, 1, 0, 0, 2, 1, 1, 0, 2, 1, 1, 0, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int64)

In [43]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [44]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
0           157
1            14
2             5
3             1
4             1
dtype: int64

In [45]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [46]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=acs2.labels_, cmap='rainbow')

In [47]:
# single linkage using l2 distance metric

In [48]:
acs3 = AgglomerativeClustering(n_clusters=5,affinity='l2',linkage='single')
Y = acs3.fit_predict(X)
Y

array([0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int64)

In [49]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [50]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
0           170
2             5
1             1
3             1
4             1
dtype: int64

In [51]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [52]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=acs3.labels_, cmap='rainbow')

In [53]:
# single linkage using cosine distance metric

In [54]:
acs4 = AgglomerativeClustering(n_clusters=5,affinity='cosine',linkage='single')
Y = acs4.fit_predict(X)
Y

array([2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 4, 3, 2, 0, 0, 2, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2,
       2, 0], dtype=int64)

In [55]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [56]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
0           105
2            66
4             3
1             2
3             2
dtype: int64

In [57]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [58]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=acs4.labels_, cmap='rainbow')

In [59]:
#average linkage using euclidean distance metric

In [60]:
aca = AgglomerativeClustering(n_clusters=5,affinity='euclidean',linkage='average')
Y = aca.fit_predict(X)
Y

array([4, 4, 2, 0, 3, 0, 2, 2, 4, 4, 0, 2, 2, 2, 0, 2, 2, 4, 0, 3, 3, 3,
       4, 4, 3, 3, 2, 2, 3, 4, 2, 0, 4, 2, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3,
       3, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 2, 1, 3, 1, 1, 1, 1, 3,
       1, 1, 3, 3, 3, 1, 1, 4, 3, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 1, 1, 1,
       3, 1, 1, 1, 1, 1, 1, 4, 1, 1, 3, 1, 3, 1, 1, 1, 3, 1, 1, 1, 1, 3,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 3, 3, 1, 1, 1, 1, 3, 1, 1, 3, 3, 1, 1, 3, 1, 1, 1, 1, 3,
       1, 3, 1, 3, 3, 1, 1, 3, 1, 3, 1, 1, 3, 3, 3, 1, 1, 1, 3, 3, 3, 3,
       3, 1], dtype=int64)

In [61]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [62]:
Y_new = pd.DataFrame(Y)
Y_new.value_counts()

1    83
3    47
4    23
2    19
0     6
dtype: int64

In [63]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [64]:
plt.figure(figsize=(10,7))
plt.scatter(X.iloc[:,0],X.iloc[:,2],c=aca.labels_,cmap='rainbow')

In [65]:
#average linkage using manhattan distance metric

In [66]:
aca1 = AgglomerativeClustering(n_clusters=5,affinity='manhattan',linkage='average')
Y = aca1.fit_predict(X)
Y

array([0, 0, 3, 1, 4, 1, 3, 3, 0, 0, 1, 3, 3, 3, 1, 3, 3, 0, 1, 0, 4, 4,
       0, 0, 0, 0, 3, 3, 0, 0, 3, 1, 0, 3, 0, 0, 0, 0, 0, 4, 4, 0, 0, 4,
       0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 0, 0, 3, 3, 2, 4, 2, 4, 2, 2, 4,
       2, 2, 4, 4, 0, 2, 2, 0, 0, 2, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4,
       4, 4, 2, 2, 2, 2, 2, 0, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 2, 4,
       4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2,
       4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 2, 4, 0, 0, 2, 4, 4, 4, 2, 2, 2, 4,
       4, 4, 2, 0, 4, 4, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 2, 2, 4, 4, 4, 0,
       0, 4], dtype=int64)

In [67]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [68]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
4           59
2           57
0           37
3           19
1            6
dtype: int64

In [69]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [70]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=aca1.labels_, cmap='rainbow')

In [71]:
#average linkage using l1 distance metric

In [72]:
aca2 = AgglomerativeClustering(n_clusters=5,affinity='l1',linkage='average')
Y = aca2.fit_predict(X)
Y

array([0, 0, 3, 1, 4, 1, 3, 3, 0, 0, 1, 3, 3, 3, 1, 3, 3, 0, 1, 0, 4, 4,
       0, 0, 0, 0, 3, 3, 0, 0, 3, 1, 0, 3, 0, 0, 0, 0, 0, 4, 4, 0, 0, 4,
       0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 0, 0, 3, 3, 2, 4, 2, 4, 2, 2, 4,
       2, 2, 4, 4, 0, 2, 2, 0, 0, 2, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4,
       4, 4, 2, 2, 2, 2, 2, 0, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 2, 4,
       4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2,
       4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 2, 4, 0, 0, 2, 4, 4, 4, 2, 2, 2, 4,
       4, 4, 2, 0, 4, 4, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 2, 2, 4, 4, 4, 0,
       0, 4], dtype=int64)

In [73]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [74]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
4           59
2           57
0           37
3           19
1            6
dtype: int64

In [75]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [76]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=aca2.labels_, cmap='rainbow')

In [77]:
#average linkage using l2 distance metric

In [78]:
aca3 = AgglomerativeClustering(n_clusters=5,affinity='l2',linkage='average')
Y = aca3.fit_predict(X)
Y

array([4, 4, 2, 0, 3, 0, 2, 2, 4, 4, 0, 2, 2, 2, 0, 2, 2, 4, 0, 3, 3, 3,
       4, 4, 3, 3, 2, 2, 3, 4, 2, 0, 4, 2, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3,
       3, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 2, 1, 3, 1, 1, 1, 1, 3,
       1, 1, 3, 3, 3, 1, 1, 4, 3, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 1, 1, 1,
       3, 1, 1, 1, 1, 1, 1, 4, 1, 1, 3, 1, 3, 1, 1, 1, 3, 1, 1, 1, 1, 3,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 3, 3, 1, 1, 1, 1, 3, 1, 1, 3, 3, 1, 1, 3, 1, 1, 1, 1, 3,
       1, 3, 1, 3, 3, 1, 1, 3, 1, 3, 1, 1, 3, 3, 3, 1, 1, 1, 3, 3, 3, 3,
       3, 1], dtype=int64)

In [79]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [80]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
1           83
3           47
4           23
2           19
0            6
dtype: int64

In [81]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [82]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=aca3.labels_, cmap='rainbow')

In [83]:
#average linkage using cosine distance metric

In [84]:
aca4 = AgglomerativeClustering(n_clusters=5,affinity='cosine',linkage='average')
Y = aca4.fit_predict(X)
Y

array([1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 4, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 1,
       1, 0], dtype=int64)

In [85]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [86]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
0           105
1            66
2             3
3             2
4             2
dtype: int64

In [87]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [88]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=aca4.labels_, cmap='rainbow')

In [89]:
# complete linkage using euclidean distance metric

In [90]:
acc = AgglomerativeClustering(n_clusters=5,affinity='euclidean',linkage='complete')
Y = acc.fit_predict(X)
Y

array([0, 0, 0, 3, 2, 3, 0, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 2, 2, 2,
       0, 0, 2, 2, 0, 0, 2, 0, 0, 3, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 4, 4, 1,
       1, 1, 2, 2, 2, 4, 1, 2, 2, 4, 4, 1, 2, 1, 4, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 4, 4, 2, 1, 4, 1, 4, 2, 1, 4, 4, 1, 4, 1, 1, 4, 1,
       1, 4, 1, 4, 4, 4, 1, 4, 4, 1, 1, 1, 4, 4, 4, 4, 4, 1, 4, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 4, 1, 1, 1, 1, 1, 4, 1,
       1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2,
       2, 1], dtype=int64)

In [91]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [92]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
1           72
0           37
2           35
4           28
3            6
dtype: int64

In [93]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [94]:
plt.figure(figsize=(10,9))
plt.scatter(X.iloc[:,1],X.iloc[:,3],c=acc.labels_,cmap='rainbow')

In [95]:
# complete linkage using manhattan distance metric

In [96]:
acc1 = AgglomerativeClustering(n_clusters=5,affinity='manhattan',linkage='complete')
Y = acc1.fit_predict(X)
Y

array([1, 1, 1, 3, 4, 3, 1, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 3, 2, 4, 4,
       1, 1, 2, 2, 1, 1, 2, 1, 1, 3, 2, 1, 1, 2, 2, 1, 1, 4, 4, 1, 1, 4,
       2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 4, 0, 0, 0, 0, 4,
       0, 0, 4, 4, 2, 0, 0, 2, 2, 0, 0, 0, 4, 0, 0, 4, 0, 0, 0, 0, 0, 0,
       4, 0, 0, 0, 0, 0, 0, 2, 0, 0, 4, 0, 4, 0, 0, 0, 4, 0, 0, 0, 0, 4,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 4, 4, 4, 0, 0, 0, 0, 4, 0, 0, 2, 2, 0, 0, 4, 0, 0, 0, 0, 4,
       0, 4, 0, 2, 4, 0, 0, 4, 0, 4, 0, 0, 4, 4, 4, 0, 0, 0, 4, 4, 4, 2,
       2, 0], dtype=int64)

In [97]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [98]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
0           83
1           37
4           33
2           19
3            6
dtype: int64

In [99]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [100]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=acc1.labels_, cmap='rainbow')

In [101]:
# complete linkage using l1 distance metric

In [102]:
acc2 = AgglomerativeClustering(n_clusters=5,affinity='l1',linkage='complete')
Y = acc2.fit_predict(X)
Y

array([1, 1, 1, 3, 4, 3, 1, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 3, 2, 4, 4,
       1, 1, 2, 2, 1, 1, 2, 1, 1, 3, 2, 1, 1, 2, 2, 1, 1, 4, 4, 1, 1, 4,
       2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 4, 0, 0, 0, 0, 4,
       0, 0, 4, 4, 2, 0, 0, 2, 2, 0, 0, 0, 4, 0, 0, 4, 0, 0, 0, 0, 0, 0,
       4, 0, 0, 0, 0, 0, 0, 2, 0, 0, 4, 0, 4, 0, 0, 0, 4, 0, 0, 0, 0, 4,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 4, 4, 4, 0, 0, 0, 0, 4, 0, 0, 2, 2, 0, 0, 4, 0, 0, 0, 0, 4,
       0, 4, 0, 2, 4, 0, 0, 4, 0, 4, 0, 0, 4, 4, 4, 0, 0, 0, 4, 4, 4, 2,
       2, 0], dtype=int64)

In [103]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [104]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
0           83
1           37
4           33
2           19
3            6
dtype: int64

In [105]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [106]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=acc2.labels_, cmap='rainbow')

In [107]:
# complete linkage using l2 distance metric

In [108]:
acc3 = AgglomerativeClustering(n_clusters=5,affinity='l2',linkage='complete')
Y = acc3.fit_predict(X)
Y

array([0, 0, 0, 3, 2, 3, 0, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 2, 2, 2,
       0, 0, 2, 2, 0, 0, 2, 0, 0, 3, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 4, 4, 1,
       1, 1, 2, 2, 2, 4, 1, 2, 2, 4, 4, 1, 2, 1, 4, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 4, 4, 2, 1, 4, 1, 4, 2, 1, 4, 4, 1, 4, 1, 1, 4, 1,
       1, 4, 1, 4, 4, 4, 1, 4, 4, 1, 1, 1, 4, 4, 4, 4, 4, 1, 4, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 4, 1, 1, 1, 1, 1, 4, 1,
       1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2,
       2, 1], dtype=int64)

In [109]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [110]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
1           72
0           37
2           35
4           28
3            6
dtype: int64

In [111]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [112]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=acc3.labels_, cmap='rainbow')

In [113]:
# complete linkage using cosine distance metric

In [114]:
acc4 = AgglomerativeClustering(n_clusters=5,affinity='cosine',linkage='complete')
Y = acc4.fit_predict(X)
Y

array([2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 3, 2, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 4, 2,
       2, 0], dtype=int64)

In [115]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [116]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
0           105
2            65
1             4
3             2
4             2
dtype: int64

In [117]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [118]:
plt.figure(figsize=(10, 7))  
plt.scatter(X.iloc[:,1], X.iloc[:,2], c=acc4.labels_, cmap='rainbow')

In [119]:
# ward linkage has only default euclidean distance metric 

In [120]:
acw = AgglomerativeClustering(n_clusters=5,affinity='euclidean',linkage='ward')
Y = acw.fit_predict(X)
Y

array([3, 3, 3, 1, 0, 1, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 1, 3, 1, 0, 0, 0,
       3, 3, 0, 0, 3, 1, 0, 3, 1, 1, 3, 1, 3, 0, 0, 3, 3, 0, 0, 3, 3, 0,
       0, 3, 3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 3, 1, 1, 2, 0, 2, 0, 4, 4, 0,
       2, 2, 0, 0, 0, 4, 2, 3, 0, 4, 4, 2, 0, 2, 4, 0, 0, 2, 2, 2, 2, 2,
       0, 0, 2, 2, 2, 4, 4, 3, 0, 4, 0, 4, 0, 2, 4, 4, 0, 4, 2, 2, 4, 0,
       2, 4, 2, 4, 4, 4, 2, 4, 4, 2, 0, 2, 4, 4, 4, 4, 4, 2, 4, 2, 0, 2,
       2, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0, 4, 0, 0, 2, 2, 2, 4, 0,
       0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2], dtype=int64)

In [121]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [122]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
0           58
2           44
3           28
4           28
1           20
dtype: int64

In [123]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [124]:
plt.figure(figsize=(10,8))
plt.scatter(X.iloc[:,2],X.iloc[:,3],c=acw.labels_,cmap='rainbow')

# KMEANS CLUSTERING

In [125]:
#using the KMeans clustering algorithm from scikit-learn on your DataFrame X with n_clusters=6. This means you are attempting to cluster your data into 6 clusters.

In [126]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=6)
kmeans.fit(X)

KMeans(n_clusters=6)

In [127]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [128]:
Y = kmeans.predict(X)
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
1           57
5           48
0           26
2           24
4           17
3            6
dtype: int64

In [129]:
kmeans.inertia_

646886.7817745255

In [130]:
# using the KMeans algorithm with a different number of clusters (from 1 to 13) and recording the inertia (within-cluster sum of squares) for each number of clusters

In [131]:
l1 = []
for i in range(1,14):
    kmeans = KMeans(n_clusters=i)
    kmeans=kmeans.fit(X)
    Y = kmeans.predict(X)
    l1.append(kmeans.inertia_)
    
print(l1)

[17591888.28194833, 4543290.204116592, 2370241.9103852804, 1332698.4482710646, 915938.5763492449, 646886.7817745255, 411702.53462852223, 322794.50358256116, 270720.4589661649, 217477.95934168046, 186502.72326557338, 159734.48267646218, 139614.1855062348]


# Elbow plot, Scree plot

In [132]:
# creating a scatter plot and overlaying a line plot to visualize the inertia values for different numbers of clusters

In [133]:
import matplotlib.pyplot as plt
plt.scatter(range(1,14),l1)
plt.xlabel = 'range(1,14)'
plt.ylabel = 'l1'
plt.plot(range(1,14),l1,color='red')
plt.show()

In [134]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [135]:
plt.figure(figsize=(10,8))
plt.scatter(X.iloc[:,1],X.iloc[:,2],c=kmeans.labels_,cmap='rainbow')

# DBSCAN CLUSTERING

In [136]:
# using the StandardScaler from scikit-learn to standardize your data

In [137]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss_X = ss.fit_transform(X)
ss_X = pd.DataFrame(ss_X)
ss_X.columns = list(X)
ss_X

Type   Alcohol     Malic       Ash
0    1.014285  1.640721  1.027946 -0.115519
1    0.965044 -0.409676  2.214331 -0.446231
2    1.394758 -0.499145 -0.346496  0.434131
3    2.334585  0.014759 -0.304787 -0.233266
4   -0.036838  1.411416 -0.138024  0.674390
..        ...       ...       ...       ...
173 -0.022230 -0.346464 -0.852727 -1.427127
174  0.009966  0.178514 -1.436780 -0.700209
175  0.281638  1.433739 -0.787093 -2.164284
176  0.297552  1.425687 -0.636259 -1.682825
177 -0.595218 -0.016114 -1.862522 -1.494781

[178 rows x 4 columns]

In [138]:
#using the DBSCAN algorithm from scikit-learn on your standardized data ss_X

In [139]:
from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps=1,min_samples=8)
dbscan.fit(ss_X)

DBSCAN(eps=1, min_samples=8)

In [140]:
Y = dbscan.labels_
Y

array([-1,  0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,
        0, -1,  0, -1,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1, -1,  0, -1,
        0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1,  0,  0,  0,  0, -1,  0,
        0, -1,  0,  0,  0, -1,  0,  0, -1,  0, -1,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, -1,  0,  0,  0,  0,  0, -1, -1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,
        0,  0, -1, -1,  0,  0,  0,  0, -1,  0,  0, -1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1, -1, -1, -1,
        0,  0,  0,  0, -1, -1,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1, -1,
        0,  0,  0,  0,  0, -1, -1,  0], dtype=int64)

In [141]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [142]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
 0          139
-1           39
dtype: int64

In [143]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [144]:
plt.figure(figsize=(10,8))
plt.scatter(X.iloc[:,1],X.iloc[:,2],c=dbscan.labels_,cmap='rainbow')

In [145]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [146]:
plt.figure(figsize=(10,8))
plt.scatter(X.iloc[:,1],X.iloc[:,3],c=dbscan.labels_,cmap='rainbow')

In [147]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [148]:
plt.figure(figsize=(10,8))
plt.scatter(X.iloc[:,0],X.iloc[:,2],c=dbscan.labels_,cmap='rainbow')

In [149]:
dbs = DBSCAN(eps=1.5,min_samples=9)
dbs.fit(ss_X)

DBSCAN(eps=1.5, min_samples=9)

In [150]:
Y = dbs.labels_
Y

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0, -1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0], dtype=int64)

In [151]:
# created a new DataFrame Y_new with a column named 'clusters' based on some clustering results.value_counts() method is then used to count the occurrences of each unique value in the 'clusters' column.

In [152]:
Y_new = pd.DataFrame(Y,columns=['clusters'])
Y_new.value_counts()

clusters
 0          170
-1            8
dtype: int64

In [153]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [154]:
plt.figure(figsize=(10,7))
plt.scatter(X.iloc[:,0],X.iloc[:,1],c=dbs.labels_,cmap='rainbow')

In [155]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [156]:
plt.figure(figsize=(10,7))
plt.scatter(X.iloc[:,3],X.iloc[:,1],c=dbs.labels_,cmap='rainbow')

In [157]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [158]:
plt.figure(figsize=(10,7))
plt.scatter(X.iloc[:,1],X.iloc[:,3],c=dbs.labels_,cmap='rainbow')

In [159]:
#creating a scatter plot using Matplotlib, where the points are colored based on cluster assignments

In [160]:
plt.figure(figsize=(10,7))
plt.scatter(X.iloc[:,1],X.iloc[:,2],c=dbs.labels_,cmap='rainbow')